repository: mark-ruddy/markruddydev.github.io
url: "https://markruddydev.github.io"
baseurl: "/"

remote_theme: jeffreytse/jekyll-theme-yat

title: Mark Ruddy Dev Blog

theme_color: "#090a0b"
night_mode: "on"
