remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme

title: mark_ruddy_security_blog
description: Some notes on things I run into in while exploring infosec.

show_downloads: false
github:
  is_project_page: false
