remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
title: Mark Ruddy Security Blog
description: Some notes on things I run into in while exploring infosec.
show_downloads: false
