repository: mark-ruddy/mark-ruddy-sec.github.io
url: "https://mark-ruddy-sec.github.io"
baseurl: "/"

remote_theme: jeffreytse/jekyll-theme-yat

title: MarkR Cybersecurity Blog

theme_color: "#090a0b"
night_mode: "on"
